### ISSUE TITLE
findOneElement - none elements found

### ISSUE THREAD

**Issue by danpritts** [famzah/google-sites-backup#1]
Hi,

Thanks for this tool.  It's crashing for me with the following error:

```
/Users/danno/googlesite/a/umich.edu/foo/backups-1/tape-library-1/__meta/saveRestore-08_14_15-144011.partaf.meta (Meta - attachment)
/Users/danno/googlesite/a/umich.edu/foo/backups-1/tape-library-1/saveRestore-08_14_15-144011.partae (Entity - attachment)
/Users/danno/googlesite/a/umich.edu/foo/backups-1/tape-library-1/__meta/saveRestore-08_14_15-144011.partae.meta (Meta - attachment)
Next page to fetch from the API? Yes.
XmlParserSitesGData::FindOneElement(link): none elements found
```

There are some largish files attached to this page.  It looks like maybe the script is crashing when it gets to the attached file blahblahblah.partad .  

Notably, google shows a "sound" icon next to this file.  "file" think's it's MPEG ADTS, layer II, v2,   8 kbps, 16 kHz, JntStereo.  (It actually isn't that, it's a split gzip of a configuration dump from my tape library.  But i guess the first few bytes match this mp2 format.)

I poked around a bit, but it looks like a bit of a rabbit hole before I'll figure it out.  I'm just going to go ahead and use the java tool, but i'm happy to test if you like.

Additional minor issue, python actually crashed when your code raised the exception.  

```
File "/Users/danno/src/google-sites-backup/google-sites-backup//backup.py", line 160, in FindOneElement
  "%s ::FindOneElement( %s ): none elements found" % cls.__name__, name
```

TypeError: not enough arguments for format string

Turns out you need an array to hold the arguments to the format string, you had omitted the `( )`.  

```
exit(
           "%s ::FindOneElement( %s ): none elements found" % \
           ( cls.__name__, name )
        )
```

**Comment by famzah** [comment]
Hi, thanks for your efforts in trying to debug this yourself. I've already fixed the TypeError bug.

Regarding the real issue here with "FindOneElement(link): none elements found". It means that in the parsed XML response by the Google API, an "entry" doesn't have a "link" element/property with an attribute 'rel' = 'alternate'. Which is strange.

The sample code "samples/sites/sites_example.py" suggests that this may happen:

``` python
if entry.GetAlternateLink():
   print ' view in Sites:\t%s' % entry.GetAlternateLink().href
```

I based my logic on the fact that every "entry" has an "alternate link", which actually is the URL address in Google Sites.

In order to debug this further:
- Do you have an idea how this file is different from the others, so that it doesn't have a URL address?
- Is this a public Google Site which I can try to backup on my side?
- If it's a private one, does the information within allows you to add me as a "read-only" user temporarily?
- If none of this work, I'll try to add a "debug" mode and ask you to submit me the state of the script when the problem occurs; this will also reveal a small part of your private data.

Please advise.

**Comment by danpritts** [comment]
Hi -

Further experimentation shows that it wasn't that particular file that was the problem.  I deleted it and the similar 5MB files and the script crashes on another page now.  un-deleting those files causes them to show up at the beginning of the list when google-site-backup grabs the site.  Now the previously "bad" file is fine, it fails later in the process.  

After a few attempts of adding and deleting things, it seems like 102 is a magic number.  102 downloaded files (files on local disk - including the "meta" files) then it dies.  

Unfortunately I cannot give you access to the site.  Happy to run debugging code, I can inspect & sanitize anything important from the output.

**Comment by famzah** [comment]
It seems that I spoke too early that this script backs up everything. I knew that some "kinds" of the Google Sites aren't supported but I was delaying to implement a backup for them until someone really needed them. You may be encountering this problem.

I reworked the script:
- added better error reporting for the unsupported feed kinds
- added an option for "debug to file" which records the raw API responses and what the script parsed as an XML structure

Please proceed as follows:
1. Run the latest version of the script and see what's the error message now. Maybe it's obvious that you have a "kind" which this script doesn't backup (yet). If that is the case, then please:
   - Find the variable `skip_unknown` and set it to `True`. Run the script again and see if it finishes successfully while issuing warnings that it doesn't know how to backup the "webattachment", "filecabinet", "listitem", or "listpage" kinds.
2. If there is still no clue, you need to enable debugging in the following line by changing `debug` to `True`:

``` python
def main():
        backup = SitesBackup(debug=False)
        backup.Run()
```

The debug files are located in the "__debug" directory.

Thank you for your testing.

**Comment by famzah** [comment]
Dan, I'm closing this bug due to lack of response.

In the meantime, I've extended the script, so that it supports the whole range of Google Site objects, added more debug info and better error messages, as well as enabled logging of the API and parse responses by default. I believe that this could have fixed your issue already. If not, please open another issue here. Thank you.

**Comment by danpritts** [comment]
Ivan -

I'm sorry for my lack of response.  I tried the current git today and it
seems to work.

thank you for your help.

Do you have a "tip jar" or paypal so I can buy you a beer?

On Tue, Oct 27, 2015 at 4:01 PM, Ivan Zahariev notifications@github.com
wrote:

> Dan, I'm closing this bug due to lack of response.
> 
> In the meantime, I've extended the script, so that it supports the whole
> range of Google Site objects, added more debug info and better error
> messages, as well as enabled logging of the API and parse responses by
> default. I believe that this could have fixed your issue already. If not,
> please open another issue here. Thank you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/famzah/google-sites-backup/issues/1#issuecomment-151626461
> .

## 

Dan Pritts
ICPSR Computing & Network Services
University of Michigan

**Comment by famzah** [comment]
Thanks. I donate the beer to someone near you whom you can share it with :)
